# Main details
title: Benjamin Tan Zhi Wei
author: GitHub User
email: benjamin.tanzw@gmail.com
description: Warrior on Earth
github_username:  benjamintzw

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
